config/routes.rb
Rails.application.routes.draw do
  
  root 'application#homepage'

  resources :users, only: [:create, :show, :edit, :update] do
    resources :posts, only: [:show, :index, :new]
    resources :favorites, only: [:index]
  end

  resources :posts, except: [:destroy]

  resources :favorites, only: [:create, :destroy]
  
  get '/signup', to: 'users#new', as: 'signup'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  delete 'images/:id/purge', to: 'posts#purge_image', as: 'delete_image'
  delete 'posts/:id', to: 'posts#destroy', as: 'delete_post'

  
end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password
    has_many :posts
    has_many :categories, through: :posts
    has_many :favorites
    belongs_to :location, optional: true # use when associated record doesn't exist and you're trying to save
    validates :username, uniqueness: { case_sensitive: false }
    validates :username, presence: true
    accepts_nested_attributes_for :location, reject_if: :all_blank # does not save location if attributes field blank

    def location_attributes=(location)
        if !(location[:state].empty? && location[:city].empty?)
            self.location = Location.find_or_create_by(state: location[:state], city: location[:city])
            self.location.update(location)
        end
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :verify_logged_in, only: [:show, :edit, :update]
    before_action :verify_user_can_view, only: [:show, :edit, :update]
    
    def new
        redirect_to posts_path if logged_in?
        @user = User.new
    end

    def show
        @user = User.find(params[:id])
    end

    def create
        @user = User.create(user_params)
        if @user.save
            set_session(@user)
            flash[:notice] = "Account successfully created"
            redirect_to posts_path
        else
            flash.now[:alert] = "Failed to create a new account"
            render :new
        end
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        if current_user.update(user_params)
            redirect_to posts_path
        else
            render :edit
        end
    end
    

    private

    def verify_user_can_view
        redirect_to posts_path unless current_user == User.find(params[:id])
    end

    def user_params
        params.require(:user).permit(:username, :email, :phone_number, :password, :password_confirmation, location_attributes: [:state, :city])
    end

end

app/views/users/_form.html.erb
<b><%= field.label :email %></b><br>
<%= field.text_field :email %>
<br><br>

<b><%= field.label :phone_number %></b><br>
<%= field.text_field :phone_number %>
<br><br>

app/views/users/edit.html.erb
<b><p class="fs-2 text-center"> Edit account for <%=@user.username%> </p></b><br><br>

<div class="container">

    <%=render partial: "shared/errors", locals: {user_post_errors: @user, message: "prevnting profile from being updated"} %>

    <%= form_for @user do |f| %>
        <%= render partial: "form", locals: {field: f}%>
        <%= render partial: "shared/location", locals: {field: f, user_post: @user}%>
    <%= f.submit "Update Account" %>
    <% end %>

</div>

app/views/users/new.html.erb
<%=render partial: "shared/errors", locals: {user_post_errors: @user, message: "preventing account from being created"} %>

<br><br><br>

<div class="card text-center">
  <div class="card-header">
  </div>
  <div class="card-body">
    <h3 class="card-title">Create your account below</h3><br><br>

    <%= form_for @user do |f| %>

      <b><%= f.label :username %></b><br>
      <%= f.text_field :username, :value => @user.username %>
      <br><br>

      <%= render partial: "form", locals: {field: f}%>

      <%= render partial: "shared/location", locals: {field: f, user_post: @user}%>

      <b><%= f.label :password %></b><br>
      <%= f.password_field :password %>
      <br><br>

      <b><%= f.label :password_confirmation %></b><br>
      <%= f.password_field :password_confirmation %>
      <br><br>

      <input type="submit" class="btn btn-primary" value="Create Account">

    <% end %>
  </div>
  <div class="card-footer text-muted">
  </div>
</div>

app/views/users/show.html.erb
<b><p class="fs-2 text-center"> <%=@user.username + "'s"%> profile </p></b><br><br>

<div class="container fs-5">
    <% if @user.email.nil? || @user.email == "" %>
        <b> No email set </b><br><br>
    <% else %>
        <b>Email: </b><br><%= (@user.email) %><br><br>
    <%end%>
    <% if @user.phone_number.nil? || @user.phone_number == ""%>
        <b> No phone number set </b><br><br>
    <% else %>
        <b>Phone: </b><br><%= @user.phone_number %><br><br>
    <%end%>
    <% if @user.location.nil? %>
        <b> No location set </b><br><br>
    <% else %>
        <b>Location: </b><br><%= (@user.location.state + ", " + @user.location.city) %><br><br>
    <%end%>
    <%= link_to "Edit Account", edit_user_path(@user), class:"btn btn-primary", method:"GET" %>
</div>

<br><br>

<b><p class="fs-2 text-center"> Your Post(s) </p></b><br><br>

<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th>Delete/Edit</th>
                <th>Date Posted</th>
                <th>Item Name</th>
                <th>Condition</th>
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
            <% current_user.posts.each do |post| %>
            <tr>
                <td><%= link_to "Delete", delete_post_path(post), class:"btn btn-primary btn-sm", method:"DELETE" %>
                or <%= link_to "Edit", edit_post_path(post), class:"btn btn-primary btn-sm", method:"GET" %></td>
                <td><%=date_created(post)%></td>
                <td><%=link_to "#{post.name} - (#{post.location.city}, #{post.location.state})", user_post_path(post.user.id, post.id)%></td>
                <td><%=post.condition%></td>
                <td><%="$ #{post.price}"%></td>
            </tr>
            <%end %>
        </tbody>
    </table>
</div>
<br><br><br><br><br>