config/routes.rb
Rails.application.routes.draw do
  
  root 'application#homepage'

  resources :users, only: [:create, :show, :edit, :update] do
    resources :posts, only: [:show, :index, :new]
    resources :favorites, only: [:index]
  end

  resources :posts, except: [:destroy]

  resources :favorites, only: [:create, :destroy]
  
  get '/signup', to: 'users#new', as: 'signup'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  delete 'images/:id/purge', to: 'posts#purge_image', as: 'delete_image'
  delete 'posts/:id', to: 'posts#destroy', as: 'delete_post'

  
end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :user
    has_many_attached :images
    belongs_to :location
    has_many :favorites
    has_many :post_categories
    has_many :categories, through: :post_categories
    validates :name, :price, :description, :condition, :quantity, presence: true #:show_phone, :phone_calls, :phone_texts, :show_email
    validates :images, attached: true
    accepts_nested_attributes_for :location, reject_if: :all_blank

    def self.conditions
        condition_types = ["new", "like new", "great", "good", "fair"]
    end

    def self.states
        states = CS.states(:us)
        states_array = []
        states.each.collect do |key, value|
            states_array << value
        end
        states_array
    end

    def self.cities
        states = CS.states(:us)
        cities = []
        keys = []
        states.each.collect do |key, value|
            state_key = key.to_s
            cities << CS.cities(state_key, "US")
        end
        cities.reduce(:concat).uniq.sort
    end

    def location_attributes=(location)
        if !(location[:state].empty? && location[:city].empty?)
            self.location = Location.find_or_create_by(state: location[:state], city: location[:city])
            self.location.update(location)
        end
    end

    def self.user_with_location(user = nil)
        includes(:location).where(location: {state: user.location.state, city: user.location.city})
        #returns active record relation object vs array with native ruby code
    end

    def self.high_to_low(user = nil)
        if !user.nil? && !user.location.nil?
            self.user_with_location(user).order("price DESC")
        else
            order("price DESC")
        end
    end
      
    def self.low_to_high(user = nil)
        if !user.nil? && !user.location.nil?
            self.user_with_location(user).order("price ASC")
        else
            order("price ASC")
        end
    end

    def self.categories_filter(current_user = nil, category_id)
        if !current_user.nil? && !current_user.location.nil?
            self.user_with_location(current_user).includes(:categories).where(categories: {id: category_id})
        else
            includes(:categories).where(categories: {id: category_id})
        end
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :verify_logged_in, only: [:new, :create, :edit, :update]
    before_action :verify_user_owns_post, only: [:edit, :update]

    def index
        @user = current_user
        @categories = Category.all
        
        if params[:user_id] #if statement for nested resource - all posts from a specific user
            @user = User.find_by(id: params[:user_id])
            if @user.nil?
                flash[:alert] =  "user not found"
                redirect_to posts_path
            else
                @posts = @user.posts
            end
        elsif !params[:categories].blank? #if statements for filtering posts
            @posts = Post.categories_filter(@user, params[:categories])
        elsif !params[:price].blank?
            if params[:price] == "Low to High"
              @posts = Post.low_to_high(@user)
            else
              @posts = Post.high_to_low(@user)
            end
        elsif logged_in? && !@user.location.nil? #when user logs in, @posts will be all posts from location if set
            @posts = Post.user_with_location(@user)
        else
            @posts = Post.all
        end
    end
    
    def new
        @post = Post.new(user_id: params[:user_id])
        #another way: @post.build_location(city: "", state: "")
    end

    def show
        if params[:user_id]
            @user = User.find_by(id: params[:user_id])
            @post = Post.find_by(id: params[:id])
            if @post.nil? #if statement for when user enters non-existing user or post id in URL
                flash[:alert] =  "post not found"
                redirect_to posts_path
            elsif @user.nil?
                flash[:alert] =  "User not found"
                redirect_to posts_path
            elsif !@user.posts.include?(@post)
                flash[:alert] = "Post does not belong to user"
                redirect_to posts_path
            end
        else
            @post = Post.find(params[:id])
        end
        @favorite = current_user.favorites.find_by(post: @post) if logged_in? #see if @post belongs to user to determine whether to display 'favorite' or 'unfavorite'
    end

    def create
        @post = Post.new(post_params)
        if @post.save
            flash[:notice] = "Successfully created post"
            redirect_to post_path(@post)
        else
            flash.now[:alert] = "Post not saved"
            render :new
        end
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])
        if @post.update(post_params)
            redirect_to post_path(@post)
        else
            render :edit
        end
    end

    def destroy
        @post = Post.find(params[:id])
        @post.delete
        redirect_to posts_path
    end

    def purge_image
        image = ActiveStorage::Attachment.find(params[:id])
        image.purge
        flash[:notice] = "Deleted Image"
        redirect_back fallback_location: root_path
    end

    private

    def verify_user_owns_post
        redirect_to posts_path unless current_user.posts.include?(Post.find(params[:id]))
    end

    def post_params
        params.require(:post).permit(:user_id, :name, :price, :description, :make_manufacturer, :model_number, :size_dimensions, :condition, :quantity, :show_phone, :phone_calls, :phone_texts, :show_email, location_attributes: [:state, :city], category_ids:[], images: [])
    end
end

app/views/posts/_form.html.erb
<!-- form_tag form_for form_with -->
<br>
<%= form_for @post do |f| %>

  <%= f.hidden_field :user_id %>

  <div class="container text-center">
    
    <b> Item Image(s) </b><br><br>
    <% if @post.images.attached? %>
        <% @post.images.each do |image| %>
          <div class="inline-block">
            <%= image_tag image, width: "200px" %>
            <p><%= link_to "Delete Image", delete_image_path(image), method: :delete %></p>
          </div>
        <% end %>
    <% end %>
    <br><br><br>
    <div>
    <b><%= f.label 'Attach Images' %><br><br></b>
    <%= f.file_field :images, multiple: true %>
    </div>
  </div>

  <div class="container text-center">
    <div class="row row-cols-2">

      <div class="col">
        <b><%= f.label 'Item Name' %><br></b>
        <%= f.text_field :name %>
        <br><br>
      </div>

      <div class="col">
        <b><%= f.label :price %><br></b>
        <%= f.number_field :price, step: 1.0 %>
        <br><br>
      </div>

      <div class="col">
        <b><%= f.label 'Make and/or Manufacturer' %><br></b>
        <%= f.text_field :make_manufacturer %>
        <br><br>
      </div>

      <div class="col">
        <b><%= f.label 'Model Name and/or Number' %><br></b>
        <%= f.text_field :model_number %>
        <br><br>
      </div>

      <div class="col">
        <b><%= f.label 'Size/Dimesions' %><br></b>
        <%= f.text_field :size_dimensions %>
        <br><br>
      </div>

      <div class="col">
        <b><%= f.label :condition %><br></b>
        <%= f.collection_select :condition, Post.conditions, :to_s, :to_s, include_blank: true%>
        <br><br>
      </div>

      <div class="col">
          <div class="form-check">
          <b><%= f.label :categories %><br></b>
          <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name)  do |b|%>
            <%= b.label class:"label-checkbox" do%>
              <%=b.check_box + " " + b.text%>
            <%end%>
          <%end%>
          <br><br>
        </div>
      </div>

      <div class="col">
        <b><%= f.label :quantity %><br></b>
        <%= f.number_field :quantity, step: 1.0 %>
        <br><br>
      </div>

      <div class="col">
        <b><%= f.label :description %><br></b>
        <%= f.text_area :description, size: "70x5" %>
        <br><br><br>
      </div>

      <div class="col">
        <%= render partial: "shared/location", locals: {field: f, user_post: @post}%>
      </div>

    </div>
  </div>

  <div class="container form-check form-switch">
    <%= f.label "Display email to public" %>
    <%= f.check_box :show_email, class: "form-check-input" %>
  </div>
  <div class="container form-check form-switch">
    <%= f.label "Display phone number to public" %>
    <%= f.check_box :show_phone, class: "form-check-input" %>
  </div>
  <div class="container form-check form-switch">
    <%= f.label "Phone calls" %>
    <%= f.check_box :phone_calls, class: "form-check-input" %>
  </div>
  <div class="container form-check form-switch">
    <%= f.label "Phone texts" %>
    <%= f.check_box :phone_texts, class: "form-check-input" %>
  </div>

  <div class="d-grid gap-2 col-1 mx-auto">
    <input type="submit" class="btn btn-primary btn-lg" value=<%=button%>>
  </div>

<% end %>
<br><br><br><br>


<%# <%=f.select :show_email, [['None', false], ['Yes', true]]%>
<%# <%=f.select :show_phone, [['None', false], ['Yes', true]]%>
<%# <%=f.select :phone_calls, [['None', false], ['Yes', true]]%>
<%# <%=f.select :phone_texts, [['None', false], ['Yes', true]]%>

<%# <input  class="form-check-input" id="post_show_email" name="post[show_email]" type="checkbox" value="1" /><input name="post[show_email]" type="hidden" value="0" /> %>

app/views/posts/edit.html.erb
<br>
<b><p class="fs-2 text-center"> Edit your post for item: <%=@post.name%> </p></b>

<%=render partial: "shared/errors", locals: {user_post_errors: @post, message: "preventing this post from being saved"} %>

<%= render partial: "form", locals: {button: "Update"} %>

app/views/posts/index.html.erb
<br><br>

<% if logged_in? && !@user.location.nil? && !params[:user_id]%>
    <b><p class="fs-2 text-center"> Showing posts from <%=@user.location.city + ", " + @user.location.state%> </p></b>
<% elsif logged_in? && params[:user_id]%>
    <b><p class="fs-2 text-center"> Showing posts from <%=@user.username%> </p></b>
<% else %>
    <b><p class="fs-2 text-center"> Showing all posts </p></b>
<%end%><br>

<div class="container">
<% if logged_in? && !params[:user_id]%>
    <button type="button" class="d-grid gap-2 col-2 mx-auto btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
        Change Location
    </button>
    <br><br>

    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Your Location</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <%= form_for @user do |f| %>
                        <%= render partial: "shared/location", locals: {field: f, user_post: @user}%>
                        <%= f.submit "Update Location" %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
<%end%>

<% if !params[:user_id]%>
    <div class="text-center">
    <h4>Filter posts:</h4><br>
    <%= form_tag("/posts", method: "get") do %>
        by <b>Category</b> <%= select_tag "categories", options_from_collection_for_select(@categories, "id", "name"), include_blank: true %>
        or by <b>Price</b> <%= select_tag "price", options_for_select(["Low to High", "High to low"]), include_blank: true %>
        <%= submit_tag "Filter" %>
    <% end %>
<% end %>
</div>
<br><br>


<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th>Date Posted</th>
                <th>Item Name</th>
                <th>Condition</th>
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
            <% @posts.each do |post| %>
            <tr>
                <td><%=date_created(post)%></td>
                <td><%=link_to "#{post.name} - (#{post.location.city}, #{post.location.state})", user_post_path(post.user.id, post.id)%></td>
                <td><%=post.condition%></td>
                <td><%="$ #{post.price}"%></td>
            </tr>
            <%end %>

        </tbody>
    </table>
</div>

app/views/posts/new.html.erb
<br>

<b><p class="fs-2 text-center"> Enter your item details </p></b>

<%=render partial: "shared/errors", locals: {user_post_errors: @post, message: "preventing this post from being created"} %>

<%= render partial: "form", locals: {button: "Create"}%>

app/views/posts/show.html.erb
<br>
<div class="container text-end">
<%if logged_in?%>
    <%if !current_user.posts.include?(@post) %>
        <%if @favorite.nil? %>
            <%= button_to "Favorite", favorites_path, params: {favorite: {post_id: @post.id}}, method: "post" %>
        <% else %>
            <%= button_to "Unfavorite", favorite_path(@favorite), method: "delete" %>
        <% end %>
    <%end%>
    <br>
    <p><%= @post.favorites.count %> favorite(s) for this post </p><br>
<%end%>
</div>

<div class="container text-center">
    <div class="fs-2">
        <b> Showing Item page for: <%=@post.name%> </b>
        <br><br>
    </div>

    <b> Item Image(s) </b><br><br>

    <% if @post.images.attached? %>
        <% @post.images.each do |image| %>
            <div class="inline-block">
            <%= image_tag image, width: "200px" %>
            </div>
        <% end %>
    <% end %>
    <br><br><br>
    
   
    <div class="row row-cols-1">
        <span class="border border-primary">
            <div class="col">
                <b>Description: </b><br><%= @post.description %><br>
                <br>
            </div>
        </span>
    </div>

    <div class="row row-cols-2">
        <span class="border border-primary">
            <div class="col">
                <b>Price: </b><br><%= "$ #{@post.price}" %><br>
                <br>
            </div>
        </span>

        <span class="border border-primary">
            <div class="col">
                <b>Location: </b><br><%= "#{@post.location.city}, #{@post.location.state}" %><br>
                <br>
            </div>
        </span>

        <span class="border border-primary">
            <div class="col">
                <b>Condition: </b><br><%= "#{@post.condition}" %><br>
                <br>
            </div>
        </span>

        <span class="border border-primary">
            <div class="col">
                <b>Make and/or Manufacturer: </b><br><%= @post.make_manufacturer %><br>
                <br>
            </div>
        </span>

        <span class="border border-primary">
            <div class="col">
                <b>Quantity: </b><br><%= @post.quantity %><br>
                <br>
            </div>
        </span>

        <span class="border border-primary">
            <div class="col">
                <b>Size/dimesions: </b><br><%= @post.size_dimensions %><br>
                <br>
            </div>
        </span>

        <span class="border border-primary">
            <div class="col">
                <b>Categories: </b><br>
                <% @post.categories.each do |category| %>
                    <%= category.name %><br>
                <% end %>
                <br>
            </div>
        </span>

        <span class="border border-primary">
            <div class="col">
                <b>Model name and/or number: </b><br><%= @post.model_number %><br>
                <br>
            </div>
        </span>
    </div>
</div>

<div class="container">
    <br><br>
    <b> Contact Details: </b><br><br>
    <b>Posted by:</b> <%= @post.user.username %><br>
    <b>Email:</b> <%= @post.user.email if @post.show_email == true %><br>
    <b>Phone:</b> <%= @post.user.phone_number if @post.show_phone == true %><br>
    <b> Phone calls: </b> <%= @post.phone_calls == true ? "Yes" : "No"  %><br>
    <b> Phone texts: </b> <%= @post.phone_texts == true ? "Yes" : "No"  %><br><br>
    <p><%=link_to "View more posts from this user", user_posts_path(@post.user)%></p>
</div>

<br><br><br><br>