config/routes.rb
Rails.application.routes.draw do
  
  root 'application#homepage'

  resources :users, only: [:create, :show, :edit, :update] do
    resources :posts, only: [:show, :index, :new]
    resources :favorites, only: [:index]
  end

  resources :posts, except: [:destroy]

  resources :favorites, only: [:create, :destroy]
  
  get '/signup', to: 'users#new', as: 'signup'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  delete 'images/:id/purge', to: 'posts#purge_image', as: 'delete_image'
  delete 'posts/:id', to: 'posts#destroy', as: 'delete_post'

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    helper_method :logged_in?
    helper_method :current_user
    helper_method :date_created

    def homepage
        redirect_to posts_path if logged_in?
    end

    private

    def set_session(user)
        session[:user_id] = user.id
    end

    def logged_in?
        !!current_user
    end

    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

    def verify_logged_in
        redirect_to root_path unless logged_in?
    end

    def date_created(post)
        post.created_at.strftime("%b %e, %Y")
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/homepage.html.erb
<br><br><br>
<div class="card text-center">
  <div class="card-header">
  </div>
  <div class="card-body">
    <h2 class="card-title">Welcome to Sell-Your-Stuff!</h5><br><br>
    <h5 class="card-text"><a href="<%=login_path%>" style="text-decoration: none;">Log In</a></h5>
    <h5 class="card-text"><a href="<%=signup_path%>" style="text-decoration: none;">Sign Up</a></h5>
    <h5 class="card-text"><a href="<%=posts_path%>" style="text-decoration: none;">Continue as Guest</a></h5>
    <br>
    <h6> or </h6>
    <form action='/auth/twitter2' method='post'>
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <button type="submit" class="btn btn-primary">Log in with Twitter</button>
    </form>
  </div>
  <div class="card-footer text-muted">
  </div>
</div>

<!--
#<%= link_to('Log in with GitHub!', '/auth/github', method: :post) %>
-->