config/routes.rb
Rails.application.routes.draw do
  
  root 'application#homepage'

  resources :users, only: [:create, :show, :edit, :update] do
    resources :posts, only: [:show, :index, :new]
    resources :favorites, only: [:index]
  end

  resources :posts, except: [:destroy]

  resources :favorites, only: [:create, :destroy]
  
  get '/signup', to: 'users#new', as: 'signup'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  delete 'images/:id/purge', to: 'posts#purge_image', as: 'delete_image'
  delete 'posts/:id', to: 'posts#destroy', as: 'delete_post'

  
end

app/views/layouts/_logged_in_nav.html.erb
<nav class="navbar fixed-top navbar-expand-lg bg-primary">
<div class="container-fluid">
  <a class="navbar-brand" style="color: white;" href="<%=posts_path%>">Sell-Your-Stuff</a>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <li class="nav-item">
        <a class="nav-link" style="color: white;" href="<%=user_path(current_user)%>">Profile</a>
      </li>
      <li class="nav-item">
        <a class="nav-link active" style="color: white;" aria-current="page" href="<%=user_favorites_path(current_user.id)%>">Favorites</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" style="color: white;" href="<%=new_user_post_path(current_user)%>"> New Post</a>
      </li>
    </ul>
    <span class="navbar-text">
      <%= link_to "Log Out", logout_path, class:"navbar-brand", method:"delete" %>
    </span>
  </div>
</div>
</nav>

app/views/layouts/_logged_out_nav.html.erb
<nav class="navbar fixed-top navbar-expand-lg bg-primary">
<div class="container-fluid">
  <a class="navbar-brand" style="color: white;" href="<%=posts_path%>">Sell-Your-Stuff</a>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>SellYourStuffApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
    <% if logged_in? %>
      <%= render 'layouts/logged_in_nav' %>
    <% else %>
      <%= render 'layouts/logged_out_nav' %>
    <% end %>
  </header>

  <body>
  
  <br><br><br>
  <div class="container-fluid text-primary">
  <% if logged_in? %>
    <b> logged in as: <%=current_user.username%> </b>
  <% end %>
  </div>

  <%if flash[:notice]%>
    <div class="alert alert-success alert-dismissible fade show" role="alert"> 
        <%= flash[:notice] %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
        </button>
      </div>
    <% elsif flash[:alert]%>
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <%= flash[:alert] %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
        </button>
      </div>
  <%end %>

  

    <%= yield %>
    

  </body>

</html>